pe002 : pe002.c
	gcc -o ../../build/pe002.d/pe002 pe002.c
	x86_64-pc-linux-gnu-gcc -o ../../build/pe002.d/pe002.exe pe002.c

clean :
	rm -f ../../build/pe002.d/pe002
	rm -f ../../build/pe002.d/pe002.exe

