/*----------------------
 * Problem 002
 * Fibonacci even sum
 * Author: Jocelyn
 * Github: jocelyn-gh/Project-Euler 
 *---------------------*/

/*-----------------------
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *----------------------*/
#include <stdio.h> 

int main(void)
{
    int fibonacciMax = 4000000; //max number targer to stop counting at once ariving or passed.
    int TotalEvensum =0; //Sum of all even Fibonacci Seqence numbers
    int currentFib=1; //current number in the Fibonacci Sequence
    int previousFib=0; //previous number in the Fibonacci Sequence
    int nextFib=0; //next number in the Fibonacci Sequence

        while(currentFib < fibonacciMax){
          
            printf("nextFib = %d + %d\n", currentFib, previousFib);         
            nextFib = currentFib + previousFib;
                       
            previousFib = currentFib;
            printf("previousFib = %d\n", previousFib);

            currentFib = nextFib;
            printf("currentFib = %d\n", currentFib);
 
            if(currentFib % 2 == 0){ 
                TotalEvensum += currentFib;
            }       
        }
    printf("total even sum = %d\n", TotalEvensum);
    return 0;
}
