pe003 : pe003.c
	gcc -o ../../build/pe003.d/pe003 pe003.c -lm
	x86_64-pc-linux-gnu-gcc -o ../../build/pe003.d/pe003.exe pe003.c -lm
clean :
	rm -f ../../build/pe003.d/pe003
	rm -f ../../build/pe003.d/pe003.exe
