pe001 : pe001.c
	gcc -o ../../build/pe001.d/pe001 pe001.c
	x86_64-pc-linux-gnu-gcc -o ../../build/pe001.d/pe001.exe pe001.c
clean :
		rm -f ../../build/pe001.d/pe001
		rm -f ../../build/pe001.d/pe001.exe

